### ISSUE TITLE
Installing the database Odoo via ansible

### ISSUE THREAD

**Issue by collex100** [michaelrigart/ansible-role-odoo#2]
Can I use the ansible to give such commands:

`$ ./odoo-bin shell`
```
$ from openerp.service import db
db.exp_create_database('dbname',False,'ru_RU','admin','admin')
```
or
`$ ./odoo-bin -d dbname -i crm,sale --without-demo=all`

If yes, then please help how it can be done.

Thanks!

**Comment by michaelrigart** [comment]
This is not possible. This role is meant to be run by using ansible and not the odoo binary script.
